# Generated by Django 5.1.1 on 2024-09-25 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_planting_date_potatocrop_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='potatocrop',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='potatocrop',
            name='activity',
            field=models.CharField(max_length=100),
        ),
    ]
